server.port=8080
spring.datasource.url=jdbc:mysql://1.92.140.185:3306/gewe?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=Asia/Shanghai&useSSL=false
spring.datasource.username=jinyue
spring.datasource.password=DFewrf#8deD
spring.datasource.driver-class-name=com.mysql.jdbc.Driver

spring.redis.host = 114.116.254.102
spring.redis.database = 15
spring.redis.port = 6379
spring.redis.password = Kcwl34567